Dockerfile
gitops/components/argo/cwfts/cwft-git.yaml

changing default entrypoint to init

---

gitops/terraform/base/eks/main.tf

Upgraded eks cluster from 1.17 to 1.20

Eks cluster upgrade

---

gitops/terraform/cypress/cypress/integration/gitlab-init.spec.js

adjustments to gitlab runner token collection process

---

gitops/terraform/base/ec2/scripts/install_gitlab.sh
gitops/terraform/cypress/cypress/integration/gitlab-init.spec.js

bugfix + upgrade gitlab 14.6.0->14.8.1

---

cmd/checktools.go
cmd/create.go
cmd/destroy.go
cmd/globals.go
cmd/init.go
cmd/installationSteps.go

Add progress bars

---

README.md
build/Dockerfile
docker-compose.yaml
scripts/kubefirst-dev.sh

feat: add docker compose to kubefirst-dev

---

cmd/argocdSync.go
cmd/clean.go
cmd/create.go
cmd/destroy.go
cmd/init.go
cmd/kubefirstTemplate.go
cmd/kubernetes.go
cmd/root.go
configs/kubefirstDirectory.go
internal/argocd/argocd.go
internal/aws/aws.go
internal/downloadManager/download.go
internal/gitlab/gitlab.go
internal/k8s/kubernetes.go
internal/softserve/softserve.go
internal/vault/vault.go
pkg/helpers.go
pkg/keys.go
pkg/progress_bar.go

chore: merge arcocdsync and clean commands

---

README.md
cmd/argocdSync.go
cmd/info.go
cmd/version.go

docs: update readme with more general details

---

cmd/init.go

fix change

---

internal/gitlab/gitlab.go
internal/terraform/terraform.go
internal/vault/vault.go
pkg/shell.go

Adding new shell choices to help on terraform calls

---

cmd/create.go

Send port-forward logs to out

---

pkg/keys.go

ran a formatter to ensure spaces instead of tabs
the only *actual* change is line 57-62

adding retry spec to argocd registry

---

internal/aws/aws.go

Enable bucket version

---

cmd/createUtils.go
cmd/destroy.go
cmd/kubernetes.go
internal/argocd/argocd.go
internal/gitlab/gitlab.go
internal/helm/helm.go
internal/k8s/kubernetes.go
internal/vault/vault.go

remove more noise from output

---

cmd/kubefirstTemplate.go
configs/config.go

Signed-off-by: johndietz <john@kubefirst.com>

static kubeconfig naming convention

---

cmd/clean.go

chore: update info screen to be non blocking screen

---

cmd/create.go
cmd/init.go
internal/reports/create.go

Improve handoff screen:
```
----------------------------------------------------------------------
Cluster "kubefirst" is up and running!:
Save this information for future use, once you leave this screen some
of this information is lost.
Press ESC to leave this screen and return to shell.
--- AWS --------------------------------------------------------------
AWS Account Id: 123456789123
AWS hosted zone name: domain.com
AWS region: sa-east-1
--- GitLab -----------------------------------------------------------
username: root
password:
Repos:
https://gitlab.domain.com/kubefirst/gitops
https://gitlab.domain.com/kubefirst/metaphor
--- Vault ------------------------------------------------------------
URL: https://vault.domain.com
token:
--- ArgoCD …
```

Address ui issues

---

cmd/create.go
internal/aws/aws.go

- Add `dry-run`. on liveliness check 
- Fix End of Installation Screen

Fix end screen

---

cmd/version.go
configs/config.go

Fix version command and version number

fix version

---

cmd/create.go
cmd/createUtils.go
cmd/init.go
internal/telemetry/telemetry.go

chore: update flag name, update logic

---

pkg/shell.go

fix shell issue

---

cmd/create.go
internal/argocd/argocd.go

- fix: there were two sync calls, this is updating the second request as well
- chore: increase sync waiting time

fix: add missing sync call, increase sync waiting time

---

internal/ssl/ssl.go

fix argocd namespace on backup ssl process

fix-argocd-ns-on-backup-ssl

---

cmd/create.go
cmd/init.go
internal/aws/aws.go
internal/gitlab/gitlab.go
internal/k8s/kubernetes.go

Exploring ways to retry cert for HTTPS on ArgoCD

Retry certs logic

---

cmd/create.go
cmd/destroy.go
cmd/root.go
configs/config.go
internal/telemetry/telemetry.go
pkg/progress_bar.go

- Makes Telemetry not panic
- Add some UI to Destroy action
- Add Dry-run mode to Destroy

Destroy improvements

---

cmd/k1-state.go
configs/config.go
go.mod
go.sum
internal/aws/aws.go

```
Usage:
kubefirst state [flags]
Flags:
--bucket-name string   set the bucket name to store the Kubefirst config file
-h, --help                 help for state
--pull                 pull Kubefirst config file to the S3 bucket
--push                 push Kubefirst config file to the S3 bucket
```

Feat state push pull

---

cmd/createGithub.go
internal/githubWrapper/github.go

Testing a wrapper for github

---

cmd/create.go
internal/gitlab/gitlab.go
pkg/helpers.go

fix: remove unecessary argo cd sync call

---

cmd/action.go
cmd/createGithub.go
cmd/githubAdd.go
cmd/githubAddValidate.go
cmd/githubPopulate.go
cmd/githubRemove.go
cmd/githubRemoveValidate.go
configs/config.go
go.mod
go.sum
internal/gitClient/git.go
internal/githubWrapper/github.go

Exploring commands for limited actions. 
Decoupling exercise. 

initial try for github cmds

---

README.md
build/Dockerfile
docker-compose.yaml

- Tweak docker to compile the cli for the users
- Add DNS to compose container

Update compose to have DNS

---

internal/gitlab/gitlab.go

Solving: #188 
Fix bad formatting yamls in code.

fix yamls tabs

---

cmd/createUtils.go
cmd/info.go
configs/config.go
internal/argocd/argocd.go
internal/gitlab/gitlab.go
internal/helm/helm.go
internal/k8s/kubernetes.go
internal/progressPrinter/progress.go
internal/ssl/ssl.go

#188 - Second attempt to fix it

#188  2nd  try - fix tabs

---

internal/gitlab/gitlab.go
internal/ssl/ssl.go

fix #194 - double encoding 

---

cmd/restoreSSL.go
internal/aws/aws.go
internal/ssl/ssl.go

fix https://github.com/kubefirst/kubefirst/issues/216

fix: improve error handling for certificate upload

---

configs/config.go
internal/downloadManager/download.go

Update dependencies to use a supported version to arm64 Apple arch.

Fix support apple silicon

---

internal/telemetry/telemetry.go

Solve #233

---

cmd/k1-state.go

- Please check #218 for more details

fix: state pull when there is no kubefirst config file #218

---

docker-compose-dev.yaml
docker-compose.yaml

fix: add missing cmd entry for docker compose

---

internal/softserve/softserve.go

chore: fix typo on installation screen

---

cmd/createGitlab.go
cmd/deployMetaphor.go
cmd/init.go
internal/reports/section.go

Add metaphor apps for gitlab flow:

Add metaphor apps

---

cmd/kubernetes.go
internal/downloadManager/download.go
internal/flagset/aws.go
internal/gitClient/git.go
internal/softserve/softserve.go
internal/terraform/terraform.go
pkg/shell.go

fix: go test warnings

---

cmd/action.go
cmd/argocdSync.go

chore: argocd command clean up

---

cmd/createGithub.go
cmd/createGitlab.go
cmd/init.go
cmd/restoreSSL.go
internal/ssl/ssl.go

#279  - Prevents restore SSL to run more than once on the same install

Address #279 issue

---

cmd/create.go
cmd/createGithub.go
cmd/createGitlab.go
cmd/createUtils.go
cmd/init.go
internal/aws/aws.go
internal/gitlab/gitlab.go
internal/k8s/kubernetes.go
internal/metaphor/metaphor.go
internal/repo/kubefirstTemplate.go
internal/reports/section.go

- Fixing issues on `dru-run` mode detected on tests
- Solve #287 
- Fix init progress bars

Address #287

---

cmd/create.go
internal/aws/aws.go
internal/state/state.go

chore: move state function to state package

---

build/Dockerfile.ci
docker-compose-test.yaml

fix(test): Integration test name

---

internal/gitlab/gitlab.go
internal/vault/vault.go
pkg/helpers.go

Refers to templates updates: 
- #337 
- #331
- #332

Update templates detoken func

---

.github/workflows/publish-docs.yaml

ci(docs): CICD - Publish docs

---

cmd/createGitlab.go
internal/argocd/argocd.go

First shot to try fix:
- #351 

#351 fix attempt

---

cmd/destroy.go
internal/argocd/argocd.go

fix: 319, disable ArgoCD auto sync before delete registry

---

pkg/constants.go

chore: add constants

---

cmd/destroy.go

- #354 to prevent issues when argo is not deployed or already destroyed. 

#354 Add flag wrapping

---

cmd/createGithub.go
cmd/createGitlab.go
internal/gitClient/git.go
internal/gitlab/gitlab.go
internal/softserve/softserve.go
pkg/helpers.go

Fix gitlab - 351

---

cmd/createGithub.go
cmd/destroy.go
internal/terraform/terraform.go

Create ECRs Repo to metaphors applications when github flavor is selected.
close: #334

terraform_ecr_GitHub_flavor

---

cmd/createGithub.go
cmd/loadTemplate.go

fix templates updates

---

pkg/helpers.go

address #393

---

cmd/k1Ready.go
internal/chartMuseum/chartChecker.go
internal/httpCommon/client.go

Attempt to get closer to fix:
- #386  
This help to add extra checks on CM status, but it seems to doesn't solve #386 yet. Some changes need to happen in template side. 

Explore #386

---

cmd/api.go
cmd/createUtils.go

minor updates while debug a ticket

chore: wording update

---

cmd/githubAdd.go
internal/githubWrapper/github.go
internal/vault/vault.go
pkg/helpers.go

Closes #398 
With this PR we create a webhook configuration in the gitops repo, set a passcode, and inform the terraform vault modules to be used on Atlantis configuration.

Fix atlantis GitHub webhook

---

cmd/api.go
cmd/createGithub.go
cmd/createGitlab.go
cmd/k1Ready.go
internal/helm/helm.go
internal/softserve/softserve.go

Addresses some bug found:
- #429 
- #434 
- Also reverted the restriction to APIs as we don't have secrets anymore on UI(Browser Console)
- Added retrial logic for steps that appears flaky on gitlabInstall

 #429 #434

---

internal/helm/helm.go

#445 issue - Issue on retry argo

---

docs/common/certificates.md
docs/common/metaphors.md
docs/common/security.md
docs/kubefirst/github/github-repositories.md
docs/kubefirst/github/vault.md
docs/kubefirst/gitlab/vault.md

some minor changes to joao's docs adjustments from pull request #391 
- hoping to merge these into #391 
- then approve and merge #391 into 1-9-release-branch
- then merge 1-9-release branch into main
- update prerelease CI to publish from main
- from that point, we can just make iterative changes to directly main

minor adjustments / first pass through new docs

---

internal/gitClient/git.go

Possible issue fix when running for the 1st 1.9.0. 

Tweak to ensure tags work as expected

---

pkg/shell.go

```
LOG: 2022/09/27 18:20:11.475675 /home/developer/app/pkg/shell.go:34: INFO: Running /home/developer/.k1/tools/terraform
LOG: 2022/09/27 18:20:11.475999 /home/developer/app/pkg/shell.go:38:  export TF_VAR_lifecycle_nodes = ****
LOG: 2022/09/27 18:20:11.476353 /home/developer/app/pkg/shell.go:38:  export AWS_PROFILE = *******
LOG: 2022/09/27 18:20:11.476755 /home/developer/app/pkg/shell.go:38:  export TF_VAR_aws_account_id = ************
LOG: 2022/09/27 18:20:11.477127 /home/developer/app/pkg/shell.go:38:  export TF_VAR_aws_region = *********
LOG: 2022/09/27 18:20:11.477466 /home/developer/app/pkg/shell.go:38:  export TF_VAR_hosted_zone_name = ******************
```

Suppress some creds to show in the logs

---

cmd/createGitlab.go
cmd/restoreSSL.go
internal/aws/aws.go
internal/ssl/ssl.go

Try to fix certs recycle issues

---

internal/aws/aws.go

Making clean proceed with clean process even if the bucket has already been deleted from the cloud.

feat(clean): Handle error 404

---

cmd/create.go
internal/argocd/argocd.go
internal/k8s/kubernetes.go

With this PR we close https://github.com/kubefirst/kubefirst/issues/422 using the k8s go SDK performing a patch operation removing self-signed cert from argo-secret.

Fix certs conflict argocd

---

README.md

docs: update readme to follow 1.9 updates

---

cmd/createGitlab.go

Fix missing feature:
- #514
- 

Feature Parity

---

cmd/createGitlab.go

Disable user setup on gitlab

---

docs/tooling/argo/cwft-ci.md
docs/tooling/argo/cwft-docker.md
docs/tooling/argo/cwft-git.md
docs/tooling/argo/cwft-helm.md
docs/tooling/argo/cwft-npm.md
docs/tooling/argo/cwft-overview.md
mkdocs.yml

Initial version of docs for CWFTs. 
Preparation for:
- #498 

Add cwft docs

---

cmd/createGithub.go
cmd/createGitlab.go
cmd/destroy.go
cmd/init.go
cmd/root.go

Fix issues of nil on informUse

---

internal/flagset/installer.go

fix addon viper when addons flag is empty

---

internal/vault/vault.go

remove escape

---

cmd/createGithub.go
cmd/createGitlab.go
cmd/destroy.go
pkg/helpers.go

fix: close/open port forward before connecting to gitlab and vault to call terraform users apply

---

cmd/init.go

chore: break if k1 folder is present before init

---

cmd/init.go
pkg/helpers.go
pkg/helpers_test.go

fix: broken k1 folder validation, and add unit tests

---

cmd/githubRemove.go
internal/github/github.go

This PR is related to issue #520

Make github be destroyed through terraform

---

cmd/create.go
cmd/createGithubK3d.go
cmd/init.go
internal/domain/telemetry.go
internal/domain/telemetry_test.go
internal/flagset/aws.go
internal/handlers/telemetry.go
internal/handlers/telemetry_test.go
internal/repo/kubefirstTemplate.go

501 localhost four

---

cmd/create.go
cmd/init.go

fix: cluster create closing the http connection at the end

---

go.mod
go.sum
pkg/ngrok.go

feat: implement ngrok library

---

internal/helm/helm.go

fix: argocd install retry logic

---

cmd/create.go
cmd/createGithubK3d.go
internal/gitClient/git.go
internal/githubWrapper/github.go
internal/k3d/secrets.go
internal/terraform/terraform.go
pkg/constants.go
pkg/ngrok.go

feat: enable atlantis webhook

---

internal/domain/telemetry_test.go
internal/flagset/init_test.go

fix: unit tests for init command

---

pkg/helpers.go

chore: provide version to detokanize process

---

README.md

docs: add local instructions

---

cmd/init.go
internal/flagset/github.go

Fix:
- #639 
Fix issue that broke gitlab installed from config files. 

Fix issue #639

---

cmd/local/prerun.go

chore: update check logic for disk space

---

cmd/local/local.go
cmd/local/prerun.go
internal/githubWrapper/github.go
internal/k8s/kubernetes.go
internal/repo/kubefirstTemplate.go
main.go
pkg/helpers.go

This PR:
- atlantis was failing in the plan/apply step because the local cluster wasnt ready (sometimes)
- it add retry functionality to wait atlantis to be ready before asking atlantis plan/apply
- wait for atlantis positive return on plan, before apply

chore: make atlantis plan apply work

---

cmd/local/postrun.go

Reverts kubefirst/kubefirst#656

Revert "removing port forward fo api"

---

configs/viperConfig.go

chore: disable kubefirst config

---

configs/viperConfig.go

fix: conflicting configuration file name

---

cmd/destroy.go

feat: add github login step for local destroy command

---

cmd/destroy.go
cmd/local/prerun.go
internal/handlers/github.go

fix: add get github data

---

cmd/init.go

Change reference to github token

---

internal/ciTools/terraform.go
internal/flagset/init_test.go

chore: clean up

---

cmd/local/postrun.go

revert break of handoff

---

cmd/create.go
cmd/destroy.go
cmd/init.go
cmd/local.go
cmd/local/local.go
cmd/local/postrun.go
cmd/local/prerun.go
configs/config.go
configs/viperConfig.go
internal/ciTools/terraform.go
internal/flagset/init_test.go
internal/gitClient/git.go
internal/github/github.go
internal/githubWrapper/github.go
internal/handlers/github.go
internal/k3d/create.go
internal/k3d/secrets.go
internal/metaphor/metaphor.go
internal/reports/section.go
internal/terraform/terraform.go
internal/vault/vault.go
pkg/helpers.go
pkg/shell.go

feat: enable github token to be accepted via env. variable

---

cmd/init.go

Set github owner with config file

---

cmd/destroyAwsGithub.go
internal/flagset/destroy.go
internal/terraform/terraform.go

Set github aws destroy

---

internal/githubWrapper/github.go

Updates github tooling to make easier to script removal of bad destroy scenarios. 

 adding tools

---

cmd/addCi.go
internal/ciTools/ci.go

Fix gitlab template references

---

internal/aws/aws.go

Some systems fail to resolve the TXT record after creation. This PR adds Google's primary DNS server as a backup (note: it's not foolproof as some networks may block Google traffic).
Example failure:
```sh
LOG: 2022/11/10 20:29:41.859639 /home/smasoud/git/kubefirst/internal/aws/aws.go:233: kubefirst-liveness.k8s.example.com
LOG: 2022/11/10 20:29:41.861470 /home/smasoud/git/kubefirst/internal/aws/aws.go:236: []
LOG: 2022/11/10 20:29:41.861616 /home/smasoud/git/kubefirst/internal/aws/aws.go:239: Could not get record name kubefirst-liveness.k8s.example.com - waiting 10 seconds and trying again: 
error: lookup kubefirst-liveness.k8s.example.com on 127.0.0.53:53: cannot marshal DNS message
LOG: 2022/11/10 20:29:51.864912 /home/smasoud/git/kubefirst/internal/aws/aws.go:233: …
```

Use Google as a backup DNS resolver

---

cmd/destroyLocalGithub.go
cmd/local/local.go
internal/gitClient/git.go
internal/metaphor/metaphor.go
internal/terraform/terraform.go
pkg/helpers.go

feat: Set backend to minio

---

cmd/destroyLocalGithub.go
internal/terraform/terraform.go
pkg/helpers.go

feat: Set backend to localhost

---

cmd/create.go
cmd/destroyLocalGithub.go
cmd/init.go
cmd/local/local.go
cmd/local/prerun.go
internal/gitClient/git.go
internal/handlers/github.go
internal/metaphor/metaphor.go
internal/terraform/terraform.go
pkg/helpers.go

this PR:
- fix an issue when atlantis is called, and the terraform plan ask for re-creation of the GitHub repositories
- fix a GitHub login issue when username and owner cannot be updated in the ~/.kubefirst file
note; we're going to clean up the code asap

feat: update tf state store

---

internal/k8s/kubernetes.go

chore: be louder on port forward errors

---

cmd/root.go

chore: remove leftover

---

cmd/clean.go

fix: unit test

---

cmd/destroyLocalGithub.go
cmd/local/local.go
pkg/helpers.go

this is a clean up PR / after release:
- make the code less verbose and cleaner
- add function documentation

refactor: move file replacement to a function

---

cmd/local/local.go
cmd/local/prerun.go
internal/wrappers/segmentIo.go

chore: add wrapper for telemetry

---

cmd/local/local.go
cmd/local/prerun.go
internal/wrappers/github.go
internal/wrappers/segmentIo.go

this PR:
- adds a wrapper for github authenticate for local (cloud update will come later)

Add wrapper for GitHub

---

cmd/local/local.go
configs/config.go
internal/downloadManager/download.go
internal/ssl/ssl.go

746 spike https local

---

cmd/destroyLocalGithub.go
cmd/local/local.go
cmd/local/postrun.go
internal/k8s/kubernetes.go
internal/k8s/wrappers.go
internal/reports/section.go
pkg/constants.go
pkg/helpers.go
pkg/ngrok.go

feat: remove port forwards (except atlantis), use ingress

---

docs/stylesheets/extra.css

add contrast to links (provided by @donnalux)

---

docs/js/gtag.js
docs/overrides/main.html
mkdocs.yml

fix Google Analytics

---

cmd/local/local.go
cmd/local/prerun.go
internal/metaphor/metaphor.go

Adds:
- #813 
- Re-allow a branch to be used with LDFlags as source for gitops repo

feat: skip metaphor #813

---

internal/reports/section.go

- make the handoff screen show the ingress endpoints instead of the port forwards of the cluster applications

feat: Add ingress endpoints to handoff screen

---

configs/config.go
pkg/helpers.go

chore: use constants for urls

---

cmd/create.go
cmd/init.go
cmd/postInstall.go
docker-compose-test.yaml
internal/argocd/argocd.go
internal/domain/telemetry.go
internal/domain/telemetry_test.go
internal/gitClient/git.go
internal/k3d/create.go
internal/k8s/kubernetes.go
internal/repo/kubefirstTemplate.go
internal/terraform/terraform.go
internal/vault/vault.go
internal/wrappers/segmentIo.go

this PR:
- fix unit test for telemetry
- use telemetry/segmentIo wrapper for cloud create
- log updates

Fix telemetry unit test

---

.github/workflows/devrel-automations.yaml

assign automatically issues labeled docs to @fharper & add it to the devrel project

add developer relations issues automations

---

internal/terraform/terraform.go

chore: fix log message

---

cmd/local/local.go
docs/tooling/kubefirst-cli.md
internal/flagset/global.go

this PR:
- update use-telemetry documentation
closes https://github.com/kubefirst/kubefirst/issues/869 

fix: provide better documentation for use-telemetry flag

---

.github/ISSUE_TEMPLATE/docs.yml

create an issue template form for the documentations

---

cmd/clean.go
main.go

this PR:
allows logs/ folder to be removed
closes #871 

fix: rm logs flag for clean command

---

internal/handlers/telemetry.go
internal/services/segment-io.go

This PR:
- implements SegmentIO Identify

Implement segmentio identify

---

pkg/helpers.go

fix #897 - vouch image for arm/x86 arch

---

cmd/local/prerun.go
internal/handlers/github.go

this PR:
- prompts the user for confirmation before opening his browser at the GitHub token screen
- creates Ngrok tunnel after the GitHbu login

feat: ask user for confirmation at github token screen

---

docs/kubefirst/local/destroy.md
docs/kubefirst/local/faq.md

feat: update local destroy to follow new command

---

cmd/create.go
cmd/destroy.go
internal/ssl/ssl.go

fix: 900 - backup SSL issue

---

internal/flagset/installer.go

fix passwordbot 'and' operator in if

---

internal/flagset/installer.go

fix passwordbot logic - unit test

---

pkg/ngrok.go
pkg/retry_logic.go

- Add retry logic to create ngrok tunnel
- Will try to create the ngrok tunnel 3 more times if the first attempt fails

feat: Add retry logic to create ngrok tunnel

---

LICENSE

update license copyright years

---

CONTRIBUTING.md

Signed-off-by: Frédéric Harper <fred@kubeshop.io>

first draft of the contributing guide (close #885)

---

cmd/createUtils.go
internal/gitClient/fileFilter.go
internal/gitClient/git.go
internal/gitlab/gitlab.go
internal/repo/kubefirstTemplate.go
internal/softserve/softserve.go
internal/terraform/terraform.go
pkg/shell.go

Solves: 
- #926 
Mitigates:
- #896 
- #363
Add a basic support for future tooling to filter files in commits based on rules.

fix: #926 and tackle #896

---

internal/addon/addon.go
internal/flagset/aws.go
internal/flagset/ci.go
internal/flagset/common.go
internal/flagset/common_test.go
internal/flagset/create.go
internal/flagset/destroy.go
internal/flagset/github.go
internal/flagset/global.go
internal/flagset/init_test.go
internal/flagset/installer.go
internal/handlers/github.go
internal/ssl/ssl.go
pkg/log.go

Improve logs

---

docs/kubefirst/local/install.md

add local dependencies (close #951)

---

docs/roadmap/index.md

add v1.11 roadmap (close #802)

---

cmd/create.go
cmd/deployMetaphor.go
cmd/destroy.go
cmd/destroyAwsGithub.go
cmd/init.go
cmd/k1Ready.go
cmd/postInstall.go
internal/aws/aws.go
internal/aws/aws_test.go
internal/flagset/aws.go
internal/flagset/installer.go
internal/gitClient/fileFilter.go
internal/reports/section.go
pkg/constants.go
pkg/helpers.go

Fix: 
- #966 
- #965
Mitigate: 
- #896 
Also, move constant to common place for more code consistence.

fix: #966 and #965 and mitigate #896

---

cmd/create.go
cmd/init.go
pkg/log.go

fix: 
- #913 
- #969 
Mitigates:
- #896

fix: #913 and #969 mitigates #896

---

cmd/backupSsl.go
cmd/createGitlab.go
cmd/destroyAwsGitlab.go
cmd/restoreSSL.go
internal/chartMuseum/chartChecker.go
internal/softserve/softserve.go
internal/state/state.go

Mitigate: 
- #896 
Also, makes `backupSSL` by default to include metaphor.

Mitigate: #896 

---

.github/workflows/promote-docs-to-prod.yaml
.github/workflows/publish-docs.yaml

master branch version is outdated, see http://bit.ly/3G7ot1D

update checkout action to v3

---

docs/js/gtag.js
docs/overrides/main.html
mkdocs.yml

cannot make Google Tag works, see https://github.com/mkdocs/mkdocs/issues/3057

switch from Google Tag to Google Analytics

---

mkdocs.yml

issues created https://bit.ly/3YJVic8

cleanup of mkdocs.yml file

---

cmd/create.go
cmd/createGitlab.go
cmd/destroyAwsGithub.go
cmd/destroyAwsGitlab.go
cmd/init.go
internal/gitlab/gitlab.go
internal/terraform/terraform.go
main.go
pkg/shell.go

Fix: 
- #1015 
- Remove weird log message on json format on main commands execution, before logger to be ready
- Update create code to handle error and update state when error happens, to ensure ELB info is collected also in bad state
- Make easier to know how to follow the logs
- Improve troubleshooting information at log in `info` mode.

fix: #1015

---

internal/argocd/argocd.go
internal/terraform/terraform.go
main.go

fix: #1022

---

cmd/local/local.go

fix: #1027 - issue on local tag clonning mechanism

---

pkg/log.go

fix: 1033 remove color codes from logs

---

docs/stylesheets/extra.css

revert to previous link color for accessibility

---

CONTRIBUTING.md

docs: update local go run for devs

---

internal/reports/section.go

reformat handoff screen

---

docs/kubefirst/FAQ.md
docs/kubefirst/local/destroy.md

docs: add new faq items

---

.github/workflows/devrel-automations.yaml

remove the auto assignation of docs issue to @fharper

---

cmd/init.go

docs: improve liveness check error message

---

docs/common/argocd.md
docs/kubefirst/github/argocd.md
docs/kubefirst/gitlab/argocd.md
docs/kubefirst/local/argocd.md
mkdocs.yml

fix: argo cd docs

---

pkg/shell.go

chore: update terraform logs to info level

---

cmd/local/destroy.go
internal/reports/command-summary.go

feat: updates destroy UI to inform the destroy progress

---

docs/kubefirst/github/explore.md
docs/kubefirst/gitlab/explore.md
docs/kubefirst/local/explore.md
mkdocs.yml

this PR:
- adds footer navigation
- title update for explore(former after install)

feat: add footer docs navigation prev/next pages

---

docs/common/terraform.md
docs/kubefirst/github/explore.md
docs/kubefirst/gitlab/explore.md
docs/kubefirst/local/explore.md

fix: details on terraform pages

---

docs/kubefirst/github/install.md
docs/kubefirst/gitlab/install.md
docs/kubefirst/local/install.md

fix: broken links with anchor

---

docs/kubefirst/local/limitations.md
mkdocs.yml

Docs info local limitations

---

cmd/init.go

chore: use wrapper call for init

---

docs/common/metaphor.md
docs/kubefirst/github/argocd.md
docs/kubefirst/github/vault.md
docs/kubefirst/gitlab/argocd.md
docs/kubefirst/gitlab/vault.md
docs/kubefirst/installer/config-file.md
docs/kubefirst/local/argocd.md
docs/kubefirst/local/vault.md

fix: #1141 -fix links

---

docs/kubefirst/github/explore.md
docs/kubefirst/github/install.md
docs/kubefirst/gitlab/install.md

fix: github install details

---

docs/common/terraform.md

fix: update gitlab references #1044

---

docs/common/argocd.md
docs/common/metaphor.md
docs/common/terraform.md
docs/common/vault.md

docs: fix broken links

---

pkg/shell.go

chore: update log

---

docs/kubefirst/github/install.md
docs/kubefirst/gitlab/install.md
docs/kubefirst/installer/config-file.md

fix: #1150  missing config install for github

---

docs/kubefirst/github/explore.md
docs/kubefirst/overview.md

fix: overview to add more local references

---

docs/kubefirst/local/explore.md

docs: add after handoff screen information for local

---

docs/common/terraform.md

fix: wrong info on terraform samples

---

docs/tooling/kubefirst-cli.md

fix: #1163 update kubefirst-cli page

---

cmd/restoreSSL.go
docs/tooling/kubefirst-cli.md

fix: #1165 update restoreSSL command description.

---

internal/reports/section.go

fix: #1153 update metaphor link

---

docs/kubefirst/local/limitations.md
docs/kubefirst/overview.md

fix: minor docs updates

---

docs/tooling/tooling-overview.md

fix: bump tools versions

---

docs/kubefirst/github/explore.md
docs/kubefirst/gitlab/explore.md

fix: update backupSSL message, metaphor default changed

---

docs/kubefirst/gitlab/credit.md
docs/kubefirst/local/credit.md

fix: harmonize formatting between all credit pages

---

docs/kubefirst/FAQ.md

feat: update discussion links to docs

---

docs/common/terraform.md

feat: add discussion links to terraform docs

---

docs/common/terraform.md
docs/common/vault.md
docs/kubefirst/FAQ.md

feat: add discussion links to vault docs

---

docs/common/metaphor.md

feat: add discussion links to metaphor docs

---

README.md

fix: main readme.md

---

internal/reports/section.go
pkg/constants.go
tests/metaphor-frontend_test.go

feat: include staging and prod on local e2e metaphor test

---

cmd/local/local.go
internal/gitClient/git.go
internal/githubWrapper/github.go
tests/github_admin_user_test.go
tests/vault_test.go

closes #1225 
p.s: I'll still work in this issue in a next PR to improve the code / clean up

Add e2e for GitHub user

---

tests/ngrok_test.go

feat: add e2e test for ngrok and github webhook

---

main.go
pkg/log.go

feat: shorter zerolog file path

---

Taskfile.yaml
cmd/local/local.go
internal/githubWrapper/github.go
internal/ssl/ssl_test.go
tests/github_admin_user_test.go
tests/vault_test.go

e2e local GitHub user creation clean up

---

tests/github_admin_user_test.go

feat: make generic user creation for local and github

---

cmd/civo/backup.go
cmd/civo/create.go
internal/civo/bootstrapSecrets.go
internal/civo/config.go
internal/civo/detokenizeCivoGithub.go
internal/civo/terraform.go
internal/downloadManager/download.go

Refactors to match proposed changes to local.

Refactor Civo validation and detokenization.

---

internal/civo/config.go
internal/k8s/exec.go
internal/k8s/types.go
internal/vault/exec.go
pkg/constants.go

- Reduces output from Vault init cycle.
- Fixes error where VaultPortForwardURL was set to argocd port.
-

Fix bug in const for vault addr, mute exec output.

---

cmd/civo/backup.go
cmd/civo/command.go
cmd/civo/create.go
cmd/civo/destroy.go
cmd/k3d/command.go
cmd/k3d/create.go
go.mod
go.sum
internal/civo/adjustDriver.go
internal/civo/bootstrapSecrets.go
internal/civo/config.go
internal/civo/detokenize.go
internal/civo/terraform.go
internal/gitlabcloud/gitlab.go
internal/k3d/config.go
internal/k8s/exec.go
internal/reports/civo.go
internal/vault/exec.go

Adds GitLab as an option for Civo deploys.

feat: gitlab option for civo

---

cmd/civo/destroy.go
cmd/k3d/create.go
cmd/k3d/destroy.go
internal/k3d/destroy.go
internal/k3d/secrets.go
internal/progressPrinter/progress.go

- Fixes issue where k3d-github would fail when running the `publish` job due to incorrect secret formatting.
- Adds progress tracking to the k3d package for create and destroy.
- Increases width of progress output to allow for messages to show.
- Cleans up k3d secret creation.
- Adds function to assist with destroying local k3d resources in terraform via minio pf.

Fix issue with k3d-github container registration, various fixes.

---

cmd/k3d/create.go

allows cluster create command to be rerun if terminal is cancelled

fix(rename): check if file exists

---

cmd/k3d/create.go
cmd/k3d/destroy.go
internal/githubWrapper/github.go
internal/gitlabcloud/gitlab.go
internal/k3d/config.go
internal/k3d/detokenize.go
internal/k3d/secrets.go
internal/k8s/exec.go

- Adds in-cluster ngrok for k3d and removes ngrok from local client.
- Cleans up progress printers for k3d create/destroy.
- Adds confmap func for k8s package.
- Fixes issue where destroy fails if create didn't finish properly.

feat: in-cluster ngrok for k3d

---

cmd/k3d/create.go

- Removes Helm install of ArgoCD for K3d.
- Adds kustomize declarative setup for ArgoCD. This is the recommended way to manage ArgoCD declaratively.
- Makes changes to fix ArgoCD Ingress, but it still redirects and will need to be fixed.

feat: self-managed argocd

---

cmd/civo/create.go
cmd/civo/destroy.go
cmd/k3d/create.go
cmd/k3d/destroy.go

- ArgoCD is now installed via kustomize from the gitops repo and managed with an app that runs after all others are synchronized.
- Fixes some broken progrss printers in civo and k3d installs.
- ArgoCD Ingress now works for Civo installs.

feat: declarative argocd config for civo

---

cmd/civo/create.go
cmd/k3d/create.go
internal/civo/config.go
internal/civo/detokenize.go
internal/k3d/config.go
internal/k3d/detokenize.go

Supports nested gitlab groups, not just top level ones.

feat: support nested gitlab groups

---

cmd/k3d/create.go
internal/k3d/config.go
internal/k3d/create.go
internal/k3d/detokenize.go
internal/k3d/secrets.go
internal/k8s/exec.go

Runs Vault in production mode for k3d installs.

feat: non-dev mode vault for k3d installs

---

cmd/civo/create.go
cmd/civo/destroy.go
cmd/k3d/create.go
cmd/k3d/destroy.go
internal/helpers/destroy.go
internal/helpers/setup.go

Evaluates whether or not a destroy is possible and informs the user.

feat: add verification before destroy

---

cmd/aws/create.go

fixes ecr auth info sent to docker-config secret
also sends same registry to metaphor so path can be added in gitops-template

fix: aws ecr auth

---

cmd/civo/create.go
cmd/k3d/create.go

Try to guard against a condition where Civo creds may be empty.

fix: guard against empty civo creds

---

cmd/civo/create.go
cmd/k3d/create.go
internal/civo/terraform.go
internal/k8s/argocd.go
internal/vault/autounseal.go

- raises all timeouts for waiting on objects to be ready
- adds logic to vault unseal for raft implementation for retry and context

fix: fix bug with vault unseal and civo install

---

internal/aws/detokenize.go
internal/civo/detokenize.go
internal/k3d/detokenize.go

associated with gitops-template changeset
https://github.com/kubefirst/gitops-template/pull/429

fix: changing token convention to ARGOCD across all stacks

---

cmd/aws/command.go
cmd/aws/quota.go
cmd/civo/quota.go
internal/aws/quota.go
internal/github/auth.go

adds aws quota command
fixes issue with gitlab token check where if `api` was present it would still check the rest when we don't need to

feat: aws quota

---

internal/gitlab/auth.go
internal/gitlab/gitlab.go

adds commands to support listing and deleting gitlab runners by group

feat: gitlab runner cmd support

---

go.mod
go.sum
main.go
pkg/helpers.go

addresses https://github.com/kubefirst/kubefirst/issues/1311

fix: logfile creation output

---

cmd/aws/command.go
cmd/civo/command.go
cmd/k3d/command.go
cmd/k3d/create.go
cmd/root.go

fixes https://github.com/kubefirst/kubefirst/issues/1095

fix: no usage output on error for better clarity

---

cmd/beta.go
cmd/root.go
cmd/vultr/command.go
cmd/vultr/create.go
cmd/vultr/destroy.go
go.mod
go.sum
internal/reports/vultr.go
internal/vultr/adjustDriver.go
internal/vultr/bootstrapSecrets.go
internal/vultr/client.go
internal/vultr/config.go
internal/vultr/detokenize.go
internal/vultr/download.go
internal/vultr/objectStorage.go
internal/vultr/terraform.go
internal/vultr/types.go
internal/vultr/vultr.go

```bash
❯ go run . beta vultr -h
kubefirst vultr
Usage:
kubefirst beta vultr [command]
Available Commands:
create      create the kubefirst platform running on vultr kubernetes
destroy     destroy the kubefirst platform
Flags:
-h, --help   help for vultr
Use "kubefirst beta vultr [command] --help" for more information about a command.
```

feat: vultr support

---

cmd/civo/destroy.go

fix: civo destroy progress print is wrong

---

cmd/digitalocean/destroy.go
cmd/vultr/destroy.go
internal/digitalocean/config.go
internal/digitalocean/kubernetes.go
internal/k3d/create.go
internal/vultr/config.go
internal/vultr/kubernetes.go

feat: remove volums for do and vultr

---

cmd/aws/create.go
cmd/civo/create.go
cmd/digitalocean/create.go
cmd/k3d/create.go
cmd/vultr/create.go

fixes bug where gitlab group id wouldn't parse on a retry after failure

fix: resolve gitlab group id parse on retry

---

.goreleaser.yaml
build/Dockerfile
build/dev/Dockerfile

fix: adjust namespace of K1Version ldflag

---

build/README.md

Brief note on using kubefirst by installing with asdf

chore: add asdf to docs

---

cmd/aws/create.go
cmd/civo/create.go
cmd/digitalocean/create.go
cmd/vultr/create.go

Addresses https://github.com/kubefirst/kubefirst/issues/1584

fix: check for git group/org flag

---

cmd/launch.go

Addresses https://github.com/kubefirst/kubefirst/issues/1600 and https://github.com/kubefirst/kubefirst/issues/1602

fix: hide atlas password in launch, strip mongo proto

---

cmd/aws/command.go
cmd/aws/create.go
cmd/civo/command.go
cmd/civo/create.go
cmd/digitalocean/command.go
cmd/digitalocean/create.go
cmd/digitalocean/destroy.go
cmd/gcp/command.go
cmd/gcp/create.go
cmd/k3d/command.go
cmd/k3d/create.go
cmd/vultr/command.go
cmd/vultr/create.go
internal/gitShim/init.go

civo gitlab and aws github tested and working 100%

feat: add https for all providers

---

cmd/aws/command.go
cmd/aws/create.go
cmd/civo/command.go
cmd/civo/create.go
cmd/digitalocean/command.go
cmd/digitalocean/create.go
cmd/digitalocean/destroy.go
cmd/gcp/command.go
cmd/gcp/create.go
cmd/k3d/command.go
cmd/k3d/create.go
cmd/vultr/command.go
cmd/vultr/create.go
internal/gitShim/init.go

Reverts kubefirst/kubefirst#1682

Revert "feat: add https for all providers"

---

internal/gitShim/init.go

I thought scott commented this stuff out but git says I did so... idk. reverting it.

revert unfamiliar commit.

---

cmd/gcp/command.go
cmd/gcp/create.go
cmd/gcp/destroy.go

if you can't force destroy the bucket then the destroy function fails and things don't clean up.

feat: add ability for force destroying buckets

---

cmd/civo/create.go

there was room for improvement even though the logic did work with the last pr

fix: add logging and hardening

---

.github/workflows/check-signed.yml

If not, it will let the user know with the steps on how to do so

ci: add a workflow to check if the commits are signed

---

README.md

This PR intends to fix the issue #1847  created
Looking forward to your review.

fix docs link in the readme

---

build/README.md

Also took the opportunity to add a TOC, and rephrase some sections.

docs: fix Linux installation for other architecture than amd

---

tools/aws-assume-role.sh

Thanks to @D-B-Hawk for the suggestion

chore: add exit code for aws assume script

---

internal/launch/cmd.go
internal/launch/constants.go

it doesn't make sense to keep cluster zero data in more permanent storage. we don't want to keep the data and should not encourage its longevity.

feat: remove the ability to run cluster zero on atlas

---

main.go

Fixes: https://github.com/kubefirst/kubefirst/issues/1966

fix: add quouta command to the bubbletea blacklist

---

.github/workflows/check-signed.yml

I also upgraded the actions/checkout GitHub Action and made the names clearer.

Fix the signing commits check GitHub workflow for PRs from forks

---

.github/workflows/check-unit-tests.yml
.github/workflows/tests.yml
cmd/k3s/create.go
cmd/logs.go
internal/k3d/menu.go

This PR adds running `go test -v -short ./...` to this repo on each commit. Uses Go as defined by the version in the `go.mod` file.
Fixes #
Create a commit and check the "Test CI" job.

Run Go tests on commits

---

.devcontainer/devcontainer.json
CONTRIBUTING.md

Provide development environment as code
Fixes #2225
- Ensure that the [dev container](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack) extension is installed to VSCode
- Open up repo in VSCode
- When prompted, reopen in container

chore: add devcontainer for local development

---

cmd/google/command.go

Fixed type - replace [Goole](https://en.wikipedia.org/wiki/Goole) with Google
Fixes #

fix(google): fix typo

---

cmd/k3d/create.go
cmd/reset.go

Update manifest source to github.com:konsturctio/manifests

feat: update vault-handler manifest source to konstructio

---

cmd/reset.go
go.mod
go.sum
main.go

bypass log directory creation if it exists,otherwise it always complains when we re-run the cmd
build the binary,test any cmd

fix: bypass if directory already exists

---

cmd/k3d/create.go
internal/gitShim/containerRegistryAuth.go

- Handles secret creation error properly `secrets "container-registry-auth" already exists`
- Added execution control for post-detokenize process

fix: retry

---

cmd/azure/command.go

Noticed a GCP reference in the Azure CLI description - changed
Fixes #

fix(azure): change GCP ref in CLI docs to Azure

---

go.mod
go.sum
internal/launch/cmd.go

change label tag for api deployment and tag the latest api
```
go run . aws create \
--alerts-email 1@gmail.com \
--domain-name kuberfu.com \
--dns-provider cloudflare \
--gitops-template-branch main \
--git-provider gitlab \
--gitlab-group ar373 \
--cluster-name rr34 \
--ami-type BOTTLEROCKET_ARM_64 --node-type m6g.large
```

fix: label for api

---

cmd/azure/command.go
cmd/beta.go
cmd/root.go

Promote Azure from `beta` to the mainline
Fixes #
```shell
go run . azure create \
--alerts-email xxx \
--github-org xxx \
--domain-name xxx \
--gitops-template-branch main
```

feat(azure): promote azure to general availability

---

README.md

These have already been moved out of beta, so just a documentation update
Fixes #

docs: move providers out of beta

---

README.md
cmd/beta.go
cmd/root.go

remove beta tag for akamai and azure as both support physical cluster

feat: remove beta

---

.github/ISSUE_TEMPLATE/bugs.yml

Azure is a first-class citizen so should be on the template
Fixes #

ci: add azure to bug template

---

internal/utilities/flags.go

Avoid Flags which are not required for k3d to install
`go run . k3d create`

fix: remove flags not required by k3d

---

cmd/info.go
cmd/launch.go
cmd/terraform.go
cmd/version.go
internal/common/common.go
internal/step/stepper.go

fix: cmd messaging

---

cmd/aws/command.go
internal/utilities/flags.go

- Fixes ami types and upgrades ami versions

fix: ami types

---

cmd/akamai/command.go
cmd/aws/command.go
cmd/azure/command.go
cmd/civo/command.go
cmd/digitalocean/command.go
cmd/google/command.go
cmd/k3d/create.go
cmd/k3s/command.go
cmd/root.go
cmd/vultr/command.go
go.mod
go.sum
internal/utilities/flags.go

Add missing flag "cluster-type" for k3d
`go run . k3d create`

fix: add missing flags

---

cmd/reset.go
go.mod
go.sum
internal/common/common.go
internal/progress/message.go
internal/progress/progress.go
internal/provision/provision.go
internal/provision/provisionWatcher.go

fixes reset cmd,add final check step,adds missing display mesaages
`go run . k3d create`
`go run . civo create ...`

Fix display msg

---

go.mod
go.sum

feat: tag latest api

---

cmd/k3d/destroy.go

- Minio port forward stops the execution when the k3d cluster gets deleted. Closing the port forward before deleting the k3d cluster and fixed the success message

fix: k3d destroy
