konstructio/kubefirst

- gitops/components/atlantis/application.yaml
- gitops/components/chartmuseum/application.yaml
- gitops/components/gitlab-runner/application.yaml
- gitops/registry/cert-manager.yaml
- gitops/registry/external-dns.yaml
- gitops/registry/external-secrets.yaml
- gitops/registry/vault.yaml
upgrade cert-manager to 1.6.1
upgrade atlantis to 3.15.0
upgrade chartmuseum to 3.4.0
upgrade external-dns to 6.0.2
upgrade external-secrets to 8.5.0
upgrade gitlab-runner to 0.36.0
upgrade vault to 1.9.2 / chart 0.18.0
> Release 1.6

- cmd/create.go
- cmd/info.go
- docker-compose.yaml
- internal/reports/command-summary.go
- internal/reports/command-summary_test.go
- internal/reports/create.go
- internal/reports/create_test.go
- adds create handoff screen
- adds docker colors support
- decrease colors to 256 to avoid color mismtach between different terminal apps
notes;
1. our `~.kubefirst` is constantly been updated, this screen version won't have all the data/services.
2. at this point in time, passwords and tokens are shown in the screen, we might want to find a better solution when it gets more mature. maybe encrypting sensitive values.
> feat: add handoff for create command

- README.md
- cmd/cluster.go
- cmd/create.go
Create a family of commands for cluster:
Changes:
`go run . create  --dry-run=true`
```bash
go run . create  --dry-run=true
Init actions: 4 expected tasks ...
LOG: 2022/07/19 16:52:27.822981 /home/developer/app/cmd/init.go:220: init started
Logging at: /home/developer/app/logs/log_1658249547.log
LOG: 2022/07/19 16:52:27.823885 /home/developer/app/pkg/helpers.go:132: Using config file: /home/developer/.kubefirst
Error: unknown command "create" for "kubefirst"
Run 'kubefirst --help' for usage.
exit status 1
```
New Command:
`go run . cluster --help`
```bash
Init actions: 4 expected tasks ...
LOG: 2022/07/19 16:51:04.343238 /home/developer/app/cmd/init.go:220: init started
Logging at: /home/developer/app/logs/log_1658249464.log
LOG: 2022/07/19 16:51:04.344766 …
```
> Add cluster command

- cmd/destroy.go
Fixes:
- Reported end of pipe message, when services are destroyed. 
- Improved defer logic, when there is a issue to create port-forward
- Redirection of all port-forward logs to the logs and away from the ui. 
> remove panic destroy

- .gitignore
- cmd/create.go
- docker-compose.yaml
- internal/argocd/argocd.go
- pkg/common.go
- add ArgoCD retry feature, it will retry to sync the application 10 times, with 6 seconds sleep each try
> ArgoCD Sync retry feature

- build/Dockerfile
Add cobra-cli and vim to the image
Signed-off-by: 6za [53096417+6za@users.noreply.github.com](mailto:53096417+6za@users.noreply.github.com)
> Adding some stuff the image

- internal/downloadManager/download.go
- pkg/common.go
*don't mind branch_name
this branch does:
- feat: doesnt stop progress if tools folder already exists
- remove unused function
> feat: doesnt stop progress if tools folder already exists

- README.md
- build/Dockerfile
- docker-compose.yaml
- allow M1 users to run Kubefirst
- README.md was also updated, and should contain the required step to start the Kubefirst installer
a quick summary:
```
1. clone this repo
2. create a .env file in the root folder containing AWS_PROFILE and AWS_REGION
3. docker compose up
4. go run . init + parameters
5. go run . cluster create
```
fix #167 
> fix: fix docker for mac M1 users

- .gitignore
- internal/argocd/argocd.go
- internal/gitlab/gitlab.go
> Fix retrial logic

- internal/aws/aws.go
- internal/ssl/ssl.go
fix #196 
we need to treat us-east-1 when creating buckets on AWS
> fix-create-bucket-ssl-us-east1

- cmd/init.go
- cmd/kubefirstTemplate.go
- internal/terraform/terraform.go
Task completed during engineering day (Kubefirst team), which allows runs spot nodes on EKS node groups.
This PR depends: https://github.com/kubefirst/gitops-template/pull/86
To enable spot instances you can use the flag: `--aws-nodes-spot` on `kubefirst init` command.
> nodes_spot

- cmd/init.go
- cmd/kubefirstTemplate.go
- internal/gitClient/git.go
Add new flag to init:
```
--template-tag v1.8.x 
```
`--template-tag` will be used when cloning repos to use a frozen tag by default the same as the current cli version. 
> Allow templates to be version controlled by tags -  #227

- .gitignore
- cmd/create.go
- at the end of the installation, upload kubefirst config file
logs output:
```
LOG: 2022/08/17 13:52:15.629188 .../kubefirst/internal/aws/aws.go:465: file uploaded to, https://s3. ... .amazonaws.com/ ... bucket name ... /.kubefirst
LOG: 2022/08/17 13:52:15.629363 .../create.go:117: Kubefirst configuration file was upload to AWS S3 at " < bucket name > " bucket name
```
fix #232 
> feat: add kubefirst config auto push to the user state store bucket

- cmd/init.go
- internal/aws/aws.go
> Bug r53 hostedzone notexist

- cmd/clean.go
- internal/aws/aws.go
- pkg/helpers.go
I started https://github.com/kubefirst/kubefirst/issues/309 , but I realised the `certs` bucket is not stored in the `kubefirst` file.
The backupSSL and restoreSSL uses creates a new bucket following the pattern `k1-<hosted zone name>` and doesn't store it in the `kubefirst` file.
This also remove the confirmation(user input) to delete buckets.
> fix: delete s3 buckets and keep state-store bucket on deletion #309

- internal/flagset/common_test.go
Testing: 
```bash 
go test  ./internal/flagset/... -v
```
Result
```bash 
=== RUN   Test_GetFlagVarName
--- PASS: Test_GetFlagVarName (0.00s)
=== RUN   Test_DefineSource_set_by_flag
2022/09/05 11:16:33 Flag(sample) set from CLI flag
--- PASS: Test_DefineSource_set_by_flag (0.00s)
=== RUN   Test_DefineSource_set_by_var
2022/09/05 11:16:33 Enviroment Variable(KUBEFIRST_SAMPLE) set - using this value for Flag(sample)
--- PASS: Test_DefineSource_set_by_var (0.00s)
=== RUN   Test_DefineSource_notSet
2022/09/05 11:16:33 Enviroment Variable(sample) not set
--- PASS: Test_DefineSource_notSet (0.00s)
=== RUN   Test_DefineSource_set_by_flag_bool
2022/09/05 11:16:33 Flag(sample) set from CLI flag
--- PASS: Test_DefineSource_set_by_flag_bool (0.00s)
PASS
ok …
```
> Adding some unit test on flagset package

- cmd/create.go
Only #337 as it was removed from #340
By design this PR enabled Installer browser UI via a Flag(opt-in). 
It uses the handoff screen to keep the UI servers on, once the user leaves the handoff screen the is closed, the API and UI servers are shotdown. 
On silent mode, it is not tested, the idea was to just start and close the servers. But maybe we may have different ideas for it. 
How to use it: 
```bash 
./kubefirst cluster create --enable-console
```
> Re-enable #337

- cmd/create.go
> #386 fix - chartmuseum not ready when metaphor is deployed. 

- internal/softserve/softserve.go
- pkg/constants.go
- make `configureSoftServe` function return errors in case of error
- `ConfigureSoftServeAndPush` is the unique caller of `configureSoftServe`, if the call to `configureSoftServe` fails, try 5 times.
closes #400 
> fix: make softserve try 5 times before failing

- internal/argocd/argocd.go
the url value was hardcoded for local tests, this PR updates it.
> fix: malformed url

- cmd/githubAdd.go
- configs/config.go
- internal/flagset/github.go
> fix: closes #414, exit gracefully when missing github token

- cmd/awsWhoami.go
To complement the assume role functionality, we are adding a new command to validate the Role and Account ID that Kubefirst is running on.
> New command whoami

- README.md
Running from the source (go run ....) needs to inform the version using `ldflags`.
We are updating the readme to cover this.
> disclaimer about running from source

- cmd/backupSsl.go
- cmd/restoreSSL.go
- internal/ssl/ssl.go
With this PR we can recycle certificates to Metaphor apps (metaphor-go, metaphor-node, metaphor-frontend).
To achieve this using the cmd the flag is: `--include-metaphor` on both commands, `backupSSL` and `restoreSSL`.
The code can be reused internally calling the function to backup or restore and inform the var `includeMetaphorApps (bool)`;
closes #442
> Recycle ssl metaphors apps

- internal/flagset/installer.go
needed until #511 is closed. we can't make users provide the password and then not honor it. we'll reintroduce the check as soon as that piece is working correctly.
> adjusting bot password github switch to optional

- internal/addon/addon.go
- internal/flagset/github.go
- internal/flagset/init_test.go
- internal/flagset/installer.go
With this PR we made an enhancement on managing the addons list on the viper file and implement tests to cover the cases: 
`kubefirst init ...`:
- with add-ons;
- without addons;
- with GitHub or; 
- with GitLab.
> Test init addons

- cmd/create.go
- cmd/init.go
- internal/domain/telemetry.go
- internal/domain/telemetry_test.go
- internal/handlers/telemetry.go
- internal/handlers/telemetry_test.go
> fix: add missing error handler

- internal/ciTools/terraform.go
Adjusting CI property on viper to allow CI redeploying after it is destroyed
> Allow CI redeploy

- cmd/create.go
- internal/gitClient/git.go
- pkg/helpers.go
> chore: add s3 backend replace

- internal/flagset/init_test.go
Set the new flags below to the init unit tests:
- --git-provider
- --github-owner
> Add new flags to unit test

- cmd/createUtils.go
- cmd/local.go
> chore: force vault port forward on failure

- cmd/create.go
- cmd/createUtils.go
- cmd/local.go
- cmd/local/local.go
- cmd/local/postrun.go
- cmd/local/prerun.go
- cmd/postInstall.go
- cmd/root.go
- internal/argocd/argocd.go
- internal/gitClient/git.go
- internal/github/github.go
- internal/githubWrapper/github.go
- internal/k3d/secrets.go
- internal/k8s/kubernetes.go
- internal/metaphor/metaphor.go
- internal/terraform/terraform.go
- internal/vault/vault.go
- pkg/constants.go
- pkg/helpers.go
This PR:
- keeps old local.go command
- adds a new local.go command
- structure the three different installation moment into functions (pre install, install, post install)
- use single source of truth for flags
- organize local into local package
- remove the conditionals to check if its local install or not
> Rewire local

- cmd/local/local.go
- cmd/local/prerun.go
- cmd/root.go
- configs/viperConfig.go
> feat: use viper standard for command inputs

- cmd/create.go
- cmd/init.go
Remove `local` references from CLOUD CLI
> remove local from cloud cli

- cmd/destroy.go
- cmd/destroyAwsGithub.go
- cmd/destroyAwsGitlab.go
- cmd/destroyLocalGithub.go
- internal/flagset/destroy.go
- internal/gitClient/git.go
- internal/terraform/terraform.go
Address:
- #695
Notes:
- We are not using the new command structure yet, this PR is meant to isolate the code and help to prepare to new future command design where follow a more vertical style. Tools per flavor of install. 
- On a later stage we may see some of this code be migrated to the new structure like `local` command.
> Fix 695 destroy

- cmd/destroy.go
at the end of the command, the output is:
```
End of execution destroy
End of execution destroy
```
> fix: remove duplicated print/stdout

- cmd/local/local.go
- cmd/local/prerun.go
- configs/config.go
> feat: make local use tagged templates

- cmd/init.go
Kubefirst init is trying to get github user even if git-provider is gitlab. To fix thus, we've included validation before calling the github API to ensure the flavor is github.
> fix: Include github validation on init

- cmd/create.go
Kubefirst init is trying to get github user even if git-provider is gitlab. To fix this, we've included validation before calling the github API to ensure the flavor is github.
> fix: Include github validation on create

- cmd/local/connect.go
- cmd/local/local.go
- cmd/local/postrun.go
- internal/k8s/kubernetes.go
- internal/k8s/portForward.go
- internal/k8s/wrappers.go
This PR:
- implements port forward for the local command using the k8s go client instead of the shell OS call
> feat: implement kubernetes go client for local command port forward

- internal/aws/aws.go
- internal/terraform/terraform.go
The load balancer and its security group are not being removed with kubefirst destroy, which causes the destroy process to fail when trying to remove the VPC from the cluster.
To mitigate this issue, functions were developed to remove the security group and load balancer (based on the cluster name tag) to proceed with the VPC destroy.
> fix: Remove ELB

- README.md
proposal is to no longer isolate install from docs. alternative approach would be to have 3 install links, one for github, one for gitlab, and one for local - open to feedback, but let's get the broken link fixed while we decide.
> fix broken install link

- cmd/postInstall.go
this PR:
- removes references to k3d/local, now all local cmd are isolated into `/local` package.
> chore: isolate postinstall to not reference local installer

- cmd/destroy.go
- cmd/init.go
- cmd/postInstall.go
- internal/argocd/argocd_test.go
- internal/flagset/installer.go
- internal/repo/kubefirstTemplate.go
- internal/reports/section.go
- internal/terraform/terraform.go
> feat: add single source of truth for k3d cloud flag

- internal/terraform/terraform.go
Removing all resources from the VPC before deleting the remaining security group, an then try to delete VPC again.
> feat: Improve Destroy

- cmd/destroyLocalGithub.go
- cmd/local/local.go
- internal/argocd/argocd.go
- pkg/helpers.go
> chore: clean up

- internal/flagset/aws.go
- internal/terraform/terraform.go
- pkg/helpers.go
Flags to allow kubefirst to create AWS EKS compute nodes with [Graviton](https://aws.amazon.com/ec2/graviton/) architecture.
This feature only supports git provider Github.
We updated the gitops-template changing apps to support the ARM chipset. PR here: 
- https://github.com/kubefirst/gitops-template/pull/179
updated Github Actions on metaphor-* to use argo bin according to the arch of runner: 
- https://github.com/kubefirst/metaphor-frontend-template/pull/21
- https://github.com/kubefirst/metaphor-go-template/pull/11
- https://github.com/kubefirst/metaphor-template/pull/17
ci-tools project/docker image used on pipelines:
- https://github.com/kubefirst/ci-tools/pull/1
docs:
- https://github.com/kubefirst/kubefirst/pull/782
> eks graviton support

- cmd/local/local.go
- cmd/local/prerun.go
- pkg/helpers.go
- pkg/ngrok.go
> feat: Detokenize ngrok

- cmd/clean.go
- cmd/info.go
- cmd/local/connect.go
- cmd/local/local.go
- cmd/local/postrun.go
- cmd/local/prerun.go
- configs/kubefirstDirectory.go
- configs/kubefirstFile.go
- go.mod
- go.sum
- internal/downloadManager/download.go
- internal/helm/helm.go
- internal/k3d/create.go
- internal/k3d/destroy.go
- internal/k3d/secrets.go
- internal/k8s/kubernetes.go
- internal/k8s/portForward.go
- internal/k8s/wrappers.go
- internal/repo/kubefirstTemplate.go
- main.go
- pkg/helpers.go
- pkg/keys.go
- pkg/log.go
- pkg/ngrok.go
- pkg/shell.go
this PR introduce log level and update current Go standard log.
It uses [zerolog](https://github.com/rs/zerolog), a simple usage example is:
```go
log.Info().Msg("hello world")
```
To make a first simple PR, this PR adds only `debug, info and panic` levels, `debug` is the default level.
Zerolog provides many other nice features as hooks, chains and log context.
This log implementation is working together with the Go standard log library to avoid changing too much files at this point.
The log level is implemented for `local` command only for the time being, and local can be called with:
```go
go run . local --log-level info
```
closes #756
> Feat introduce log levels fork

- cmd/create.go
- internal/aws/aws.go
- internal/k8s/kubernetes.go
- internal/terraform/terraform.go
Major change:
- https://github.com/kubefirst/kubefirst/issues/804
- Add some AWS cloud info after install is completed, informations such as: vpcId, ELB Name and ELB SG. 
- Replace the way destroy removes ELB and its SG
> fix: destroy elb

- cmd/local/local.go
- cmd/local/postrun.go
- cmd/local/prerun.go
- configs/config.go
- internal/argocd/argocd.go
- internal/k3d/secrets.go
- internal/k8s/kubernetes.go
- Change gitops-branch to add-ingress-localhost
- Remove certificate secret creation from postrun and move it to local.go
- Move the installation of argocd ingressroute.yaml to local.go and create a new ingress to force redirect connections from argocd to https
- Fix vault endpoint to use https instead of http
- Force creation of kubefirst and minio namespaces at start of installation, thus allowing certificate secrets to be created at beginning
- Remove some unnecessary annotations from argocd ingress
> feat: add redirect to https from ingress

- internal/k8s/portForward.go
- internal/k8s/wrappers.go
> #845 - add retry logic

- internal/terraform/terraform.go
Due the use of the same variable of Terraform Output for KeyID and KMS ARN, there's garbage from keyId loading with KMS ARN. Made new variable to store KMS ANS.
> fix: Create new terraform output variable

- internal/flagset/installer.go
Added validation on init cmd regarding the length of the bot's password to avoid the terraform error on the installation's last steps.
fix #898
> added validation on bot password when is gitlab flavor

- cmd/local/local.go
- cmd/local/prerun.go
- internal/progressPrinter/progress.go
Solves: 
- #919 
- #918 
Sample:
```bash 
./kubefirst local --gitops-branch main --skip-metaphor
2022/12/15 16:49:30 kubefirst started
Logging at: /app/logs/log_1671122970.log
Download dependencies         ... 33.3% [#########...................] [1 in 300.923ms]
Download dependencies         ... done! [3 in 6.305s]
Create SSH keys               ... done! [1 in 6.313s]
Clone and Detokenize (GitOps) ... done! [1 in 7.015s]
- initialization step is done!
Process Parameters            ... done! [1 in 7.242s]
- Telemetry info sent
- Creating github resources with terraform
- Created gitops Repo in github.com/-------
- pushing local detokenized gitops content to new remote github.com/kxdroid
Setup gitops on github        ... done! [3 in 1m4.027s]
- create initial argocd repository
- helm repo …
```
> fix: ui cli issues

- internal/github/github.go
- internal/terraform/terraform.go
Terraform provider needs to know which region to use to authenticate to AWS, if the region doesn't exist in the AWS shared file, it must be informed in another way.
An alternative is to include the region informed by the installer flag as an AWS_REGION environment variable, on this way terraform provider will be able to identify the correct version through the flag.
> fix: Include env var for region

- cmd/create.go
- cmd/createGithub.go
- cmd/destroyAwsGithub.go
- cmd/githubAdd.go
- cmd/k1Ready.go
- cmd/local/destroy.go
- cmd/local/local.go
- internal/github/github.go
- pkg/destroy.go
Fix: 
- #867 
Mitigates: 
- #896
The core change is here: 
https://github.com/kubefirst/kubefirst/compare/upd_destroy_clouds_221220?expand=1#diff-d39c1b78ba45da9a30e27d6d6e428e16a69ffb2661cfb4a99e0db3fe63f955d9R159-R176
- reuse of local destroy mode to `aws-github`
> fix: #867 ensure SSH key is removed post-destroy

- docs/stylesheets/extra.css
the original color contrast isn't accessible for people with impart vision and people with monochromacy
> revert main color scheme, except for the links in the pages

- cmd/create.go
- cmd/createGithub.go
- cmd/createGitlab.go
- cmd/init.go
- cmd/local/local.go
- cmd/local/prerun.go
Fix: 
- #1053 
Sample of the output:
```bash 
-----------
Follow your logs with:
tail -f  /app/logs/log_1673272819.log
-----------
- Sending installation telemetry
Download dependencies         ... 33.3% [#########...................] [1 in 700.264ms]
Download dependencies         ... done! [3 in 8.862s]
Create SSH keys               ... done! [1 in 8.874s]
Clone and Detokenize (GitOps) ... done! [1 in 10.085s]
- initialization step is done!
Process Parameters            ... done! [1 in 10.34s]
- Creating github resources with terraform
- Created gitops Repo in github.com/ABC
- pushing local detokenized gitops content to new remote github.com/ABC
Setup gitops on github        ... done! [3 in 1m5.548s]
- create initial argocd repository
- helm repo add argo …
```
> fix: 1053 - remove bars for telemetry

- docs/kubefirst/local/install.md
> docs: explain why and how kubefirst uses ngrok and atlantis

- cmd/local/prerun.go
this PR: set metaphor-branch to main if in development mode, if metaphor-branch not set
closes #1113 
> feat: set metaphor-branch to main if in development mode

- internal/gitlab/gitlab.go
During the provisioning, the logs and bars seem to freeze, and nothing is happening due to the logs inside a loop (`for`) aren't logged.
> refactor - change the old log library to the new one

- .github/workflows/publish-docs.yaml
Problem: Node.js 12 actions are deprecated on publish docs action.
Fix: Update python setup to latest version, which has Node.js 16.
> feat: update nodejs

- Taskfile.yaml
- tests/metaphor-frontend_test.go
> feat: add e2e tests for metaphor local and cloud

- tests/vault_test.go
```
// This test does:
//   - login to the cloud vault
//   - make sure the login was successful
//   - retrieve kbot secret
//   - logout of the cloud vault
//   - login to the cloud vault again using kbot credentials and userpass flow
//   - make sure the kbot is logged in
test run:
PASS
ok  	github.com/kubefirst/kubefirst/tests	4.368s <---------
```
😮 
> feat: extend vault e2e test for local

- internal/flagset/common_test.go
- internal/flagset/init_test.go
This PR replaces `os.Setenv` with `t.Setenv`. Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
Reference: https://pkg.go.dev/testing#T.Setenv
```go
func TestFoo(t *testing.T) {
// before
os.Setenv(key, "new value")
defer os.Unsetenv(key)
// after
t.Setenv(key, "new value")
}
```
> test: use `t.Setenv` to set env vars in tests

- main.go
- pkg/helpers.go
Addresses: https://github.com/kubefirst/kubefirst/issues/1221
> Exclude log helper output from specific subcommands.

- docs/community/index.md
- internal/progressPrinter/progress.go
Signed-off-by: echoboomer <scott@echoboomer.net>
There were a couple spots that still referenced legacy naming. While the link to open Issues does redirect properly, it was still worth removing these.
> Remove legacy refs to prior package name.

- cmd/civo/civo.go
- internal/civo/bootstrapSecrets.go
- internal/gitClient/git.go
Small PR to fix the following errors:
```bash 
internal/gitClient/git.go:195:3: (*github.com/rs/zerolog.Event).Msgf format %s reads arg #3, but call has 2 args
internal/gitClient/git.go:209:3: (*github.com/rs/zerolog.Event).Msgf format %s reads arg #3, but call has 2 args
internal/gitClient/git.go:363:18: (*github.com/rs/zerolog.Event).Msgf call has arguments but no formatting directives
internal/gitClient/git.go:370:19: (*github.com/rs/zerolog.Event).Msgf call has arguments but no formatting directives
internal/civo/bootstrapSecrets.go:45:18: (*github.com/rs/zerolog.Event).Msgf call has arguments but no formatting directives
internal/civo/bootstrapSecrets.go:60:18: (*github.com/rs/zerolog.Event).Msgf call has arguments but no formatting directives
cmd/civo/civo.go:230:19: …
```
> fix: UT errors

- cmd/civo/civo.go
- go.mod
- go.sum
- internal/k8s/exec.go
Signed-off-by: Scott Hawkins <scott@echoboomer.net>
Implements a few new Kubernetes functions for working with resources. I think moving forward this would be a better blueprint for handling similar issues versus parsing flags from the config.
```bash
2023-02-13T20:14 INF internal/k8s/exec.go:34 > Waiting for vault StatefulSet to be created.
2023-02-13T20:14 INF internal/k8s/exec.go:83 > Waiting for StatefulSet vault to be ready. This could take up to 60 seconds.
2023-02-13T20:14 INF internal/k8s/exec.go:97 > All Pods in StatefulSet vault are ready.
LOG: 2023/02/13 20:14:43.625777 /Users/scott/src/kubefirst/internal/k8s/portForward.go:94: Namespace for PF vault
LOG: 2023/02/13 20:14:43.626065 /Users/scott/src/kubefirst/internal/k8s/portForward.go:95: Name for PF vault-0
2023-02-13T20:14 …
```
> bugfix: Implement wait for vault readiness to fix bug.

- cmd/civo/validate.go
- configs/config.go
- docs/tooling/tooling-overview.md
Addresses a bug where gitops repo webhook consistently failed. Also matches a recent update to the gitops-templates repo where we standardized github provider and terraform versions.
> Bump Terraform version for local client use.

- cmd/civo/destroy.go
- internal/argocd/argocd.go
- internal/civo/config.go
- pkg/constants.go
- Fixes ref to old kubeconfigpath viper entry.
- Adds func to return dynamic port forward url for Argo based on use.
-
> Fix bug in civo destroy workflow.

- cmd/civo/command.go
- cmd/civo/quota.go
- The independent `civo quota` command can now be run by providing the cloud region flag or it defaults to NYC1 just like the top level command. This fixes an error where it wouldn't work if resources hadn't been deployed yet and the flag wasn't available via inheritance.
- States in the output now that quotas are healthy instead of just a blank line.
> Add cloudregion flag to civo quota command, cleanup output.

- cmd/civo/destroy.go
- cmd/civo/quota.go
- internal/civo/bootstrapSecrets.go
- Fixes bug where secret name for git runner wasn't correct between the two providers.
- Fixes bug where destroy progress tracker didn't finish properly.
- Expands quota parameters checked for civo.
> bugfix: fix error without git runner creation

- cmd/civo/command.go
- cmd/civo/create.go
In its current state, the installer doesn't provide the github owner info which breaks auth for Docker push and pull.
> bugfix: github username missing from civo installer

- internal/vault/autounseal.go
Shows key as 1, 2, or 3 now instead of just the index. Also only uses 3 shards on each unseal to avoid more than necessary.
> enhancement: fix vault unseal logic and output

- cmd/civo/create.go
- cmd/civo/destroy.go
- cmd/k3d/create.go
- cmd/k3d/destroy.go
- internal/k8s/helpers.go
- Adds check to k3d and civo to determine if ports are already in use that are required for port forwards. Exits if so.
- Attempts to delete GitLab subgroups, but this will only work on tiers below premium. It doesn't error out if it doesn't work, it just says to delete the group manually.
> feat: check for existing port forwards, delete gitlab groups

- cmd/civo/command.go
- cmd/civo/create.go
- cmd/k3d/command.go
- cmd/k3d/create.go
- internal/vault/autounseal.go
- Updates `--github-owner` to `--github-user` for k3d.
- Updates `--github-owner` to `--github-org` for Civo.
- Updates `--gitlab-owner` to `--gitlab-group` for both.
- Adds progress printer for CoreDNS wait step for Civo to avoid no output while it waits.
- Adds some more wait logic to the Vault unseal process.
These commands were used for testing:
`go run . k3d create --git-provider gitlab --gitlab-group kubefirstdev`
`go run . k3d create --git-provider github --github-user echoboomer` (GITHUB_TOKEN set)
`go run . k3d create` (no GITHUB_TOKEN set)
```bash
go run . civo create \
--alerts-email scott@kubeshop.io \
--domain-name k-ray.space \
--git-provider github \
--github-org k-ray-space \
--cluster-name k-ray-space
```
```bash
go run . civo create \
--alerts-email scott@kubeshop.io \ …
```
> feat: update git flags, minor vault fixes

- cmd/civo/create.go
- cmd/k3d/create.go
- internal/gitlabcloud/gitlab.go
Gets the currently authenticated user's username and sets that to `GITLAB_USER`.
> feat: gitlab username parse for setting GITLAB_USER

- cmd/action.go
- cmd/civo/destroy.go
- cmd/k3d/create.go
- cmd/k3d/destroy.go
- internal/argocd/argocd.go
- internal/helpers/tls.go
- internal/reports/local.go
This allows a user to still use the k3d/local one-liner install without needing to run `mkcert -install` prior to running anything. They can still optionally run `mkcert -install` (which is feedback given during handoff) to trust certs, but it won't break install.
> fix: allow fetching argocd token over http

- cmd/aws/create.go
- cmd/aws/destroy.go
- internal/aws/destroy.go
- internal/reports/aws.go
Implements a function that removes all security groups associated with an EKS cluster as well as any ELBs associated with the cluster prior to `terraform destroy`.
Also implements handoff for AWS.
> fix: fix aws destroy logic

- cmd/civo/create.go
- cmd/k3d/destroy.go
- internal/civo/objectStorage.go
Adds a conditional check that returns an error and removes created credentials if any of the fields in the request to get Civo credentials are empty.
Also comments out the pre-destroy check for k3d.
> feat: remove civo creds if specific fields fail to parse

- cmd/civo/create.go
reduces civo to raft with a single replica until a better solution is created to manage high-availability
> fix: reduce civo to single vault replica

- cmd/aws/destroy.go
- cmd/civo/destroy.go
- cmd/k3d/destroy.go
trying to remove duplication of this message on destroy
looks like there's 3 refs for this categoty - adjusting in hopes this will accommodate
> remove duplicate output from destroy

- cmd/civo/command.go
- cmd/civo/root-credentials.go
- cmd/k3d/command.go
- cmd/k3d/destroy.go
- cmd/k3d/root-credentials.go
- internal/gitlab/gitlab.go
- internal/helpers/destroy.go
- internal/helpers/root-credentials.go
- internal/helpers/setup.go
- internal/helpers/types.go
- internal/k8s/exec.go
- internal/k8s/kubernetes.go
- internal/k8s/wrappers.go
syntax cleanup and fixing static check errors as well.
only implements `root-credentials` for `k3d` and `civo` for now
> feat: root-credentials command

- cmd/aws/create.go
- cmd/aws/destroy.go
- cmd/civo/backup.go
- cmd/civo/create.go
- cmd/civo/destroy.go
- cmd/k3d/create.go
- cmd/k3d/destroy.go
- cmd/reset.go
- internal/helpers/setup.go
- main.go
logging hint will come directly from `cmd/` subdirs from now on and will only show up on things like `create`, `destroy`, etc. this avoids the hint dropping on things like `--help`, etc.
> fix: move logging hint to func, reduce where called

- cmd/reset.go
- internal/k8s/apply.go
should handle https://github.com/kubefirst/kubefirst/issues/1248
protects against running `reset` if resources haven't been cleaned up
> fix: protection reset from running if resources are live

- cmd/aws/create.go
- cmd/civo/create.go
- cmd/civo/destroy.go
as configured, running `destroy` for either `aws` or `civo` won't destroy cloud resources if that apply step failed. this fixes that.
> fix: allow destroy civo/aws tf on tf fail

- main.go
- pkg/helpers.go
With these changes, the `OpenBrowser` func never returns anything other than `nil`. If there is an error, it is one of either:
`2023-04-11T10:44 WRN pkg/helpers.go:387 > unable to load the browser, unsupported platform - continuing`
`2023-04-11T10:44 WRN pkg/helpers.go:387 > unable to load the browser - continuing`
This will prevent failed installs due to the inability to open the browser. The user can get the link to the console from the report at the end.
> Fix disable browser open

- cmd/k3d/command.go
- cmd/k3d/create.go
Best approach I could come up with for adding https only support while retaining the most critical ssh functionality without a ton of bloat and following existing patterns. Open to changing pretty much anything. I wouldn't consider this a breaking change, because the cli should default to ssh if the flag isn't provided 
This PR relies on 
GitOps-Template PR: https://github.com/kubefirst/gitops-template/pull/498
Runtime PR: https://github.com/kubefirst/runtime/pull/51
https://github.com/kubefirst/kubefirst/issues/1566
> Git protocol opinion

- .github/workflows/tests.yml
I will deactivate it from the GitHub interface. That will prevent errors on empty YAML GitHub Action Workflow file. If it's not needed anymore, we can just delete it, let me know.
> ci: remove comments

- .github/workflows/codeql-analysis.yml
Autobuild wasn't working anymore for our code, so I replaced it with manual building step
> ci: fix kubefirst build for CodeQL analysis

- cmd/k3d/create.go
closes #1765 
a failed push during create is causing minio refs to incorrectly point at minio.kubefirst.dev which is only available to the cluster host. this fixes the auth so minio refs end up pointed at the internal minio.minio.svc.cluster.local
> fix: k3d gitops repo minio references

- cmd/gcp/create.go
This is an example fix for a problem involving the composition of FQINs for the metaphor image from subcomponents. 
It has been tested with GKE + ghcr in particular, but may break [other instances where `<CONTAINER_REGISTRY_URL>`](https://github.com/search?q=repo%3Akubefirst%2Fgitops-template%20%22%3CCONTAINER_REGISTRY_URL%3E%22&type=code) is used.
It might also be reasonable to consider something like https://github.com/kubefirst/gitops-template/pull/549 if the pattern `platform-registry` analogous to `gcp-github` would also attempt to account for `aws-ecr` and `gcp-gar` as appears to currently be the case for `aws-github`.
---
Given a FQIN for a ghcr-hosted container image constructed of subcomponents
| URL      | ghorg       | repo       |   | tag    | …
> fix: `ContainerRegistryURL` to template `<CONTAINER_REGISTRY_URL>` in association with `-p containerRegistryURL` usage

- cmd/aws/create.go
- cmd/civo/create.go
- cmd/digitalocean/create.go
- cmd/gcp/create.go
- cmd/vultr/create.go
The env var was not populated
fixes #1770
> fix: write dnsprovider tokens via vault terraform

- cmd/aws/create.go
- cmd/civo/create.go
- cmd/digitalocean/create.go
- cmd/gcp/create.go
- cmd/k3d/create.go
- cmd/vultr/create.go
it was broken everywhere if you supplied the `--gitops-template-repo` and the `--gitops-template-branch` as well as if you left off the `.git` in our default gitops-template url.
> fix: capture edge case on gitops repo/ branch flag and fix broken branch logic

- cmd/aws/create.go
This PR replicates #1774, which was gcp-only, for aws based on the reports by @alechp .
> fix: aws containerRegistryURL metaphor duplication

- .github/workflows/check-markdown.yml
- .markdownlint.json
- README.md
- build/README.md
Also fixed some Markdown issues
> ci: add a workflow to validate Markdown syntax

- .commitlint.json
- .commitlintrc.js
- .github/workflows/check-commits.yml
This will fix the annoying GitHub Action failure after a PR is merged
> ci: don't include PR number is commit linting lenght for titles

- .github/ISSUE_TEMPLATE/bugs.yml
We are starting to have more OS specific issues, this will save us time to have the information right away.
> chore: add a field for the OS for bug reports

- .github/ISSUE_TEMPLATE/bugs.yml
Useful when the issue is happening inside kubefirst, and not on the user's computer.
> chore: add a 'none specific option for OS'

- cmd/k3d/mkcert.go
- cmd/k3d/root-credentials.go
- cmd/k3d/vault.go
- cmd/letsencrypt.go
- cmd/reset.go
- internal/progress/message.go
- internal/progress/progress.go
- main.go
Fixes:
https://github.com/kubefirst/kubefirst/issues/1883
https://github.com/kubefirst/kubefirst/issues/1902
> fix: hanging commands

- cmd/aws/command.go
- cmd/civo/command.go
- cmd/google/command.go
- cmd/vultr/command.go
somehow didn't push this with the last PR
> add node type and node count flags to aws, civo, google, and vultr

- .github/ISSUE_TEMPLATE/bugs.yml
We can know which marketplace it is from the selected cloud.
> chore: make installation type for marketplace generic for bug report

- cmd/beta.go
- cmd/k3s/command.go
- cmd/k3s/create.go
- internal/progress/message.go
- internal/types/flags.go
- internal/utilities/flags.go
- internal/utilities/utilities.go
So the Merge request is dropped at least for starting some review and some test from your side 
what it's being made 
- **CLI**
- add k3s support based on your new cli design (had to keep some args for compatibilty issue, could be managed in a another ways on next iteration)
- some news args are used to manged K3S install from terraform 
~- `--k3s-extra-conf "--disable traefik,--write-kubeconfig-mode 0644,--flannel-iface eth1"`~
~- `--k3s-servers-ips 10.0.0.11,10.0.0.12,10.0.0.13`~
-~ `--k3s-ssh-private-key ~/.ssh/id_ed25519`~
~- `--K3s-agents-ips` (optionals if you want agent+ server~
~- `--k3s-ssh-user vagrant`~
- `--extra-servers-args`
- `--servers-private-ips`
- `--servers-public-ips` usefulle when u have VPS/vm with public ip
- `--servers-private-ips` LAN network eg: …
> feat: Add k3s provisionning

- cmd/k3d/create.go
- go.mod
- go.sum
Fixes: K3D and ssh
Fixes: https://github.com/kubefirst/kubefirst/issues/2112
> fix: k3d and ci flag

- internal/launch/constants.go
2.4.4 introduced rootless and privledged-free talos distribution to the kubefirst management cluster on github and gitlab versions of civo cloud provisions.
> 2.4.4 - adoption of talos distro on civo github and civo gitlab management clusters

- cmd/k3d/create.go
- cmd/logs.go
- cmd/root.go
- internal/k3d/menu.go
in stty there is echo option which is set off when bubbletea is working,so if we do bubbletea.Quit() it sets it to on and then quits
> added bubbletea quit method instead of os exit

- .editorconfig
> chore: add support for editorconfig

- CONTRIBUTING.md
It's not new information, it should have been done a while ago.
> docs: update the local testing to reflect latest changes in the process

- cmd/akamai/command.go
added pro feature flag which was missing (also refer [https://github.com/konstructio/kubefirst-api/compare/akamai-upgrade?expand=1](url) and [https://github.com/konstructio/gitops-template/compare/main...akamai-upgrade](url))
build the kubefirst binary locally and have kubefirst-api running locally,and run "./kubefirst beta akamai --alerts-email <ALERTS_EMAIL> --github-org <GITHUB_ORG> --gitops-template-branch akamai-upgrade --domain-name <DOMAIN_NAME> --cluster-name <CLUSTER_NAME>"
> fix: akamai

- cmd/reset.go
- go.mod
- go.sum
Handle the nil value of viperfile content
Fixes #2282 
build the binary and run "./kubefirst reset"
> fix reset cmd

- internal/launch/cmd.go
After running `kubefirst launch up` twice, there was no message 
Fixes https://linear.app/konstruct/issue/KRA-19/failure-for-ui-install-command-kubefirst-launch-up
- Run `kubefirst launch up`
- Once its done and try to run again `kubefirst launch up`
- Warning should show up to run `kubefirst launch down`
> fix: launch deployed message

- CONTRIBUTING.md
- README.md
- cmd/root.go
- internal/common/common.go
- internal/progress/message.go
Update doc links from `https://docs.kubefirst.io/` to `https://kubefirst.konstruct.io/docs/`
Run the following command in the current branch
```
$ go run main.go --help
kubefirst management cluster installer provisions an
open source application delivery platform in under an hour.
checkout the docs at https://kubefirst.konstruct.io/docs/.
```
> feat: update doc links to kubefirst.konstruct.io/docs

- cmd/k3d/destroy.go
when we do "kubefirst k3d destroy",it doesnt delete the k1dir repo which return an error that "repo already exists" when we try to provision a k3d cluster again and the cleanup path is also wrong one, it should be (config.K1Dir + "<cluster_name>/kubeconfig")
Provision a Kubefirst in k3d environment
Clone the repo
run:
```bash
go build .
./kubefirst k3d destroy
```
> fix: delete k1dir instead of kubeconfig file

- cmd/azure/command.go
- cmd/azure/create.go
This makes the resource group for Azure DNS optional.
Once accepted, this will require an update of the designs of the console to remove the required field on the Azure DNS section @donnalux @CristhianF7 
Fixes #2338 
1. Ensure that the CLI and API branches are loaded (see #2330 for branches)
2. Add a `replace` in the CLI's `go.mod`
```go
replace (
github.com/konstructio/kubefirst-api => ../kubefirst-api
)
```
3. Run the normal command without the `--dns-azure-resource-group` flag:
```shell
go run . beta azure create \
--alerts-email <email> \
--github-org <org> \
--domain-name <domain> \
--gitops-template-branch sje/azure-optional-dns
```
```shell
go run . beta azure create \
--alerts-email <email> \
--domain-name <domain> \
--git-provider gitlab \
--gitlab-group <group> \ …
```
> fix(azure): make the dns resource group optional

- cmd/reset.go
First PR! 🎉 
This removes the `.kubefirst` file that lives at the root alongside the `.k1` directory. Without removing this file, kubefirst hangs after validating git configuration and never tries to spin up the local cluster for initial setup if there is a partially completed run gumming things up.
Fixes #reset
Couldn't find any existing tests 🤔
> fix: delete kubefirst file when doing kubefirst reset - KRA-73

- internal/utilities/utilities.go
pass `CF_ORIGIN_CA_ISSUER_API_TOKEN` env to API.
Not able to use Cloudflare origin issuer when `CF_ORIGIN_CA_ISSUER_API_TOKEN` is set.
Add following lines to print cloudflare auth after `CreateMgmtCluster` func signature in `internal/provisio/provision.go`
```go
log.Printf("got cluster record. Value is")
jclusterRecord, err := json.Marshal(clusterRecord.CloudflareAuth)
if err != nil {
return fmt.Errorf("Unable to conver cluster record tojson")
}
log.Print(string(jclusterRecord))
os.Exit(1)
```
> fix: pass CF_ORIGIN_CA_ISSUER_API_TOKEN to API

- cmd/akamai/command.go
- cmd/akamai/create.go
- cmd/azure/command.go
- cmd/azure/create.go
- cmd/civo/command.go
- cmd/civo/create.go
- cmd/digitalocean/command.go
- cmd/digitalocean/create.go
- cmd/google/command.go
- cmd/google/create.go
- cmd/k3d/command.go
- cmd/k3d/create.go
- cmd/k3s/command.go
- cmd/k3s/create.go
- cmd/vultr/command.go
- cmd/vultr/create.go
All of the commands had flags that were never used. There's a function to pull them so we're leveraging that instead. 
The `k3d` cluster creation had a `--github-user` flag that was being validated, checked but not handled at all (after validation the program would say: "yep, all good!")
Fixes #
> Housekeeping: delete barely used flags.

- cmd/generate.go
- cmd/root.go
- internal/generate/files.go
- internal/generate/scaffold.go
- internal/generate/scaffold/{{ .AppName }}.yaml
- internal/generate/scaffold/{{ .AppName }}/Chart.yaml
- internal/generate/scaffold/{{ .AppName }}/values.yaml
- internal/generate/scaffold_test.go
- internal/generate/testdata/scaffold/development/app.yaml
- internal/generate/testdata/scaffold/development/app/Chart.yaml
- internal/generate/testdata/scaffold/development/app/values.yaml
- internal/generate/testdata/scaffold/production/metaphor.yaml
- internal/generate/testdata/scaffold/production/metaphor/Chart.yaml
- internal/generate/testdata/scaffold/production/metaphor/values.yaml
- internal/generate/testdata/scaffold/some-environment/some-app.yaml
- internal/generate/testdata/scaffold/some-environment/some-app/Chart.yaml
- internal/generate/testdata/scaffold/some-environment/some-app/values.yaml
Adds the `generate app-scaffold` command. Tried to make this as generic as possible because the users are unlikely to have a `values.yaml` file that matches Metaphor
Fixes https://github.com/konstructio/kubefirst-api/issues/488
Run the app:
```bash
go run . generate app-scaffold # will prompt for name
go run . generate app-scaffold -n app # will generate in ./registry
go run . generate app-scaffold -n app --output-path /tmp/my-app # will generate in /tmp/my-app
go run . generate app-scaffold -n app --environment hello,world # will only generate environments "hello" and "world"
```
> Generate app scaffold from CLI

- internal/launch/cmd.go
Running the `kubefirst reset` command wipes the `./k1` directory, removing the kubeconfig file but leaving the k3d cluster intact.  
This functionality ensures that the kubeconfig file is recreated if it is missing, providing seamless operation even after a reset.
1. Run the `kubefirst reset` command to clear the `./k1` directory.  
2. Use the CLI to provision a management cluster.  
3. Verify that the kubeconfig file is recreated and the cluster can be accessed without errors.
> fix: kubeconfigfile creation

- cmd/akamai/create.go
- cmd/aws/create.go
- cmd/azure/create.go
- cmd/civo/create.go
- cmd/digitalocean/create.go
- cmd/google/create.go
- cmd/k3s/create.go
- cmd/vultr/create.go
- internal/provision/provision.go
We use the same code block across all cloud providers for provisioning a management cluster. This extract that into a common location so that all of the clouds use the exact same flow.
Fixes #
With the Acceptance test suite.
> refactor: extract provisioning logic into external function to reduce duplication

- cmd/akamai/command.go
- cmd/akamai/create.go
- cmd/aws/command.go
- cmd/aws/create.go
- cmd/azure/command.go
- cmd/azure/create.go
- cmd/civo/command.go
- cmd/civo/create.go
- cmd/digitalocean/command.go
- cmd/digitalocean/create.go
- cmd/google/command.go
- cmd/google/create.go
- cmd/k3d/create.go
- cmd/k3s/command.go
- cmd/k3s/create.go
- cmd/vultr/command.go
- cmd/vultr/create.go
- go.mod
- internal/catalog/catalog.go
- internal/provision/provision.go
This moves the logic of creating the management cluster into a separate struct.
Fixes #
Automated acceptance test - Commands to CLI are running the provisioning process
> refactor: create services for each cloud KRA-72

- cmd/akamai/command.go
- cmd/akamai/create.go
- cmd/aws/command.go
- cmd/aws/create.go
- cmd/azure/command.go
- cmd/azure/create.go
- cmd/civo/command.go
- cmd/civo/create.go
- cmd/digitalocean/command.go
- cmd/digitalocean/create.go
- cmd/google/command.go
- cmd/google/create.go
- cmd/k3s/command.go
- cmd/k3s/create.go
- cmd/launch.go
- cmd/root.go
- cmd/vultr/command.go
- cmd/vultr/create.go
- internal/launch/cmd.go
- internal/provision/provision.go
- main.go
Signed-off-by: nathan-nicholson <nathan@konstruct.io>
Since the differences between clouds are minimal, extra structs are overhead.
Create Provisioner struct that's used across commands.
Fixes #
> refactor: remove cloud specific services KRA-72

- cmd/root.go
- internal/launch/cmd.go
Display the error message for cli
Example cmd to show the error :
```go run . k3s create --git-provider gitlab  --gitlab-group ar373 --alerts-email 1@gmail.com --dns-provider cloudflare --domain-name kubefirst.xyz```
> fix: display error messages
